name: ci
on: 
  push:
    branches:
      - github_action 
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORKING_DIR }}

      - name: Fetch dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y libelf-dev libssl-dev libcap-dev linux-tools-`uname -r`
          git submodule update --init --recursive

      - name: Build
        run: bazel build //src:all //src/quipper:all

      - name: Test
        run: bazel test //src:all //src/quipper:all

